services:
  - type: web
    name: linear-time
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        generateValue: true
      - key: PORT
        value: "8001"
      - key: DATABASE_URL
        fromDatabase:
          name: linear-time-db
          property: connectionString
      - key: ADMINMAIL
        sync: false
      - key: ADMINPASS
        sync: false
      - key: MAILER_URL
        value: "null://localhost"
      - key: MAILER_FROM
        value: "Linear Time <no-reply@example.com>"
      - key: TRUSTED_PROXIES
        value: "127.0.0.1,localhost"

    disk:
      name: kimai-data
      mountPath: /opt/kimai/var
      sizeGB: 1

databases:
  - name: linear-time-db
    plan: free
